version: '3'
services:

  db:
    container_name: ${REDIS_HOSTANME}
    hostname: ${REDIS_HOSTANME}
    image: redislabs/rejson:latest
    ports:
      - ${REDIS_PORT}:6379
    command: >
      --name ${REDIS_HOSTANME}
      --requirepass ${REDIS_PASSWORD} 
      --save 60 1
      --loglevel warning
    volumes:
      - tradingvolume:/data
    networks:
      - trading
      
  api:
    container_name: ${API_HOSTNAME}
    hostname: ${API_HOSTNAME}
    build:
      context: ./api
      dockerfile: api.dockerfile
    ports:
      - 4231:8080
    networks:
      - trading
    environment:
      - REDIS_HOSTNAME=${REDIS_HOSTANME}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  ui:
    container_name: ${UI_HOSTNAME}
    hostname: ${UI_HOSTNAME}
    build:
      context: ./ui
      dockerfile: ui.dockerfile
    ports:
      - ${UI_EXTERNAL_PORT}:8080
    networks:
      - trading
    environment:
      - API_HOSTNAME=${API_HOSTNAME}
      - API_PORT=${API_PORT}

volumes:
  tradingvolume:

networks:
  trading:
