version: '3'
services:

  db:
    container_name: ${REDIS_HOSTANME}
    hostname: ${REDIS_HOSTANME}
    image: redislabs/rejson:latest
    ports:
      - ${REDIS_PORT}:6379
    command: >
      --name ${REDIS_HOSTANME}
      --requirepass ${REDIS_PASSWORD} 
      --save 60 1
      --loglevel warning
    volumes:
      - tradingvolume:/data
    networks:
      - trading
      
  api:
    container_name: ${API_HOSTNAME}
    hostname: ${API_HOSTNAME}
    build:
      context: .
      dockerfile: image.dockerfile
    ports:
      - 4545:8080
    networks:
      - trading
    environment:
      - REDIS_HOSTNAME=${REDIS_HOSTANME}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}

volumes:
  tradingvolume:

networks:
  trading:
