version: '3'
services:

  db:
    container_name: ${REDIS_HOSTANME}
    hostname: ${REDIS_HOSTANME}
    image: redis:6.2.3-alpine
    restart: unless-stopped
    expose:
      - ${REDIS_PORT}
    command: >
      --requirepass ${REDIS_PASSWORD} 
      --port ${REDIS_PORT}
      --save 60 1
      --loglevel warning
    volumes:
      - tradingvolume:/data
    networks:
      - trading
      
  api:
    container_name: tradingapi
    hostname: tradingapi
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: api.dockerfile
    ports:
      - ${API_PORT}:8080
    networks:
      - trading
    environment:
      - REDIS_HOSTNAME=${REDIS_HOSTANME}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  ui:
    container_name: ${UI_HOSTNAME}
    hostname: ${UI_HOSTNAME}
    restart: unless-stopped
    build:
      context: ./ui
      dockerfile: ui.dockerfile
    ports:
      - ${UI_EXTERNAL_PORT}:8080
    networks:
      - trading
    environment:
      - API_HOSTNAME=${API_HOSTNAME}
      - API_PORT=${API_PORT}

volumes:
  tradingvolume:

networks:
  trading:
